[package]
name = "mdlog"
version = "0.2.0"
authors = ["felix girke <\"felix.girke@tu-dortmund.de\">"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
structopt = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rand = "0.7"
